### PR TITLE
#150915333 Delete contributions

### PR DESCRIPTION
**Pull request by Andela-ddiei**
#### What does this PR do?
- Adds delete contributions functionality.
#### Description of Task to be completed?
- Create delete contribution controller
- Write unit tests
#### How should this be manually tested?
At the root of the project directory run the following command:
```$pytest -v```
#### What are the relevant pivotal tracker stories?
 [#150915333](https://www.pivotaltracker.com/story/show/150915333)

### CODE REVIEW

**Comment by LarryWachira** [comment]
Rebase @Andela-ddiei

**Comment by Andela-ddiei** [comment]
@LarryWachira done

**Comment by dennomwas** [comment]
LGTM

**Comment by andela-uibrahim** [comment]
LGTM

**Comment by LarryWachira** [comment]
LGTM

**Pull request merged**
