### PR TITLE
#150880176 Separate notification, comments and votes tests from contributions.py file

### PR DESCRIPTION
**Pull request by dennomwas**
### What does this PR do?

Chore to remove notification, comments and votes tests from the contribution.py  file

### Description of Tasks completed
- Add contribution tests to test_contributions.py
- Add notifications tests to test_notifications.py
- Add comment tests to test_comments.py
- Add vote tests to test_votes.py

#### How should this be manually tested? 

After cloning the repo cd into it and run;
```
pip install -r requirements.txt
```

#### To run the tests
```
DB_TYPE=sqlite pytest
```
#### What are the relevant pivotal tracker stories? ####
#150880176

### CODE REVIEW

**Comment by andela-oowonikoko** [comment]
@dennomwas Please rebase your branch :thank_you:

**Comment by LarryWachira** [comment]
Rebase @dennomwas

**Comment by dennomwas** [comment]
@LarryWachira @andela-oowonikoko Rebased, please review for merge.....

**Comment by LarryWachira** [comment]
@dennomwas I think you should drop the extra commit.

**Comment by wanjiku-carol** [comment]
LGTM

**Comment by Andela-ddiei** [comment]
Please squash your commits

**Comment by Andela-ddiei** [comment]
LGTM

**Comment by andela-ojoloko** [comment]
please squash your commits.

**Comment by LarryWachira** [comment]
LGTM

**Pull request merged**
