### PR TITLE
#151168452: Setup Redis for notification

### PR DESCRIPTION
**Pull request by BolajiOlajide**
#### What does this PR do?
Setup Redis for notification

#### Description of Task to be completed?
While making use of the [Flask-Redis](https://github.com/underyx/flask-redis) package, we should connect the application to redis which would be used to store notification details.

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#151168452](https://www.pivotaltracker.com/story/show/151168452)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by Andela-ddiei** [comment]
Please rebase @BolajiOlajide

**Comment by Mnickii** [comment]
@BolajiOlajide we are using redis as is, as opposed to a redis ORM.

**Comment by BolajiOlajide** [comment]
Is it safe to delete the PR now @Mnickii ??

**Comment by Mnickii** [comment]
Not delete it, maybe close it until other members agree to delete. @georgreen @dennomwas @Andela-ddiei

**Comment by Andela-ddiei** [comment]
I don't think we need this anymore since to set up SSE, we had to @georgreen had to set up Redis.

**Comment by Mnickii** [comment]
@BolajiOlajide then it can be deleted.

**Pull request closed without merging**
